suppressPackageStartupMessages({
  
  library(ggplot2)
  library(targets)
  library(tibble)
  library(data.table)
  library(tarchetypes)
  library(data.table)
  library(ggplot2)
  library(stringr)
  library(iNEXT)
  library(ggpubr)
  library(viridis)
  library(visNetwork)
  library(quarto)
  library(testthat)
  library(posterior)
  library(brms)
  library(sjPlot)
  library(bayesplot)
  library(tidyverse)
  library(tidybayes)
  library(patchwork)
  library(SpadeR)
  library(vegan)
  library(boot)
  library(goeveg)
  library(RFLPtools)
  library(ggforce)
  library(concaveman)
  library(stringr)
  library(ggrepel)
  library(sf)
  library(rempsyc)
  
  
})

print('Cleared packages')

